var annotated_dup =
[
    [ "Catch", "namespaceCatch.html", [
      [ "Benchmark", "namespaceCatch_1_1Benchmark.html", [
        [ "Detail", "namespaceCatch_1_1Benchmark_1_1Detail.html", [
          [ "bootstrap_analysis", "structCatch_1_1Benchmark_1_1Detail_1_1bootstrap__analysis.html", "structCatch_1_1Benchmark_1_1Detail_1_1bootstrap__analysis" ],
          [ "ChronometerConcept", "structCatch_1_1Benchmark_1_1Detail_1_1ChronometerConcept.html", "structCatch_1_1Benchmark_1_1Detail_1_1ChronometerConcept" ],
          [ "ChronometerModel", "structCatch_1_1Benchmark_1_1Detail_1_1ChronometerModel.html", "structCatch_1_1Benchmark_1_1Detail_1_1ChronometerModel" ],
          [ "CompleteInvoker", "structCatch_1_1Benchmark_1_1Detail_1_1CompleteInvoker.html", null ],
          [ "CompleteInvoker< void >", "structCatch_1_1Benchmark_1_1Detail_1_1CompleteInvoker_3_01void_01_4.html", null ],
          [ "CompleteType", "structCatch_1_1Benchmark_1_1Detail_1_1CompleteType.html", "structCatch_1_1Benchmark_1_1Detail_1_1CompleteType" ],
          [ "CompleteType< void >", "structCatch_1_1Benchmark_1_1Detail_1_1CompleteType_3_01void_01_4.html", "structCatch_1_1Benchmark_1_1Detail_1_1CompleteType_3_01void_01_4" ],
          [ "repeater", "structCatch_1_1Benchmark_1_1Detail_1_1repeater.html", "structCatch_1_1Benchmark_1_1Detail_1_1repeater" ]
        ] ],
        [ "Benchmark", "structCatch_1_1Benchmark_1_1Benchmark.html", "structCatch_1_1Benchmark_1_1Benchmark" ],
        [ "Chronometer", "structCatch_1_1Benchmark_1_1Chronometer.html", "structCatch_1_1Benchmark_1_1Chronometer" ],
        [ "Environment", "structCatch_1_1Benchmark_1_1Environment.html", "structCatch_1_1Benchmark_1_1Environment" ],
        [ "EnvironmentEstimate", "structCatch_1_1Benchmark_1_1EnvironmentEstimate.html", "structCatch_1_1Benchmark_1_1EnvironmentEstimate" ],
        [ "Estimate", "structCatch_1_1Benchmark_1_1Estimate.html", "structCatch_1_1Benchmark_1_1Estimate" ],
        [ "ExecutionPlan", "structCatch_1_1Benchmark_1_1ExecutionPlan.html", "structCatch_1_1Benchmark_1_1ExecutionPlan" ],
        [ "OutlierClassification", "structCatch_1_1Benchmark_1_1OutlierClassification.html", "structCatch_1_1Benchmark_1_1OutlierClassification" ],
        [ "SampleAnalysis", "structCatch_1_1Benchmark_1_1SampleAnalysis.html", "structCatch_1_1Benchmark_1_1SampleAnalysis" ],
        [ "Timing", "structCatch_1_1Benchmark_1_1Timing.html", "structCatch_1_1Benchmark_1_1Timing" ]
      ] ],
      [ "Clara", "namespaceCatch_1_1Clara.html", [
        [ "Detail", "namespaceCatch_1_1Clara_1_1Detail.html", [
          [ "BasicResult", "classCatch_1_1Clara_1_1Detail_1_1BasicResult.html", "classCatch_1_1Clara_1_1Detail_1_1BasicResult" ],
          [ "BoundFlagLambda", "structCatch_1_1Clara_1_1Detail_1_1BoundFlagLambda.html", "structCatch_1_1Clara_1_1Detail_1_1BoundFlagLambda" ],
          [ "BoundFlagRef", "structCatch_1_1Clara_1_1Detail_1_1BoundFlagRef.html", "structCatch_1_1Clara_1_1Detail_1_1BoundFlagRef" ],
          [ "BoundFlagRefBase", "structCatch_1_1Clara_1_1Detail_1_1BoundFlagRefBase.html", "structCatch_1_1Clara_1_1Detail_1_1BoundFlagRefBase" ],
          [ "BoundLambda", "structCatch_1_1Clara_1_1Detail_1_1BoundLambda.html", "structCatch_1_1Clara_1_1Detail_1_1BoundLambda" ],
          [ "BoundManyLambda", "structCatch_1_1Clara_1_1Detail_1_1BoundManyLambda.html", "structCatch_1_1Clara_1_1Detail_1_1BoundManyLambda" ],
          [ "BoundRef", "structCatch_1_1Clara_1_1Detail_1_1BoundRef.html", "structCatch_1_1Clara_1_1Detail_1_1BoundRef" ],
          [ "BoundValueRef", "structCatch_1_1Clara_1_1Detail_1_1BoundValueRef.html", "structCatch_1_1Clara_1_1Detail_1_1BoundValueRef" ],
          [ "BoundValueRef< std::vector< T > >", "structCatch_1_1Clara_1_1Detail_1_1BoundValueRef_3_01std_1_1vector_3_01T_01_4_01_4.html", "structCatch_1_1Clara_1_1Detail_1_1BoundValueRef_3_01std_1_1vector_3_01T_01_4_01_4" ],
          [ "BoundValueRefBase", "structCatch_1_1Clara_1_1Detail_1_1BoundValueRefBase.html", "structCatch_1_1Clara_1_1Detail_1_1BoundValueRefBase" ],
          [ "ComposableParserImpl", "classCatch_1_1Clara_1_1Detail_1_1ComposableParserImpl.html", "classCatch_1_1Clara_1_1Detail_1_1ComposableParserImpl" ],
          [ "fake_arg", "structCatch_1_1Clara_1_1Detail_1_1fake__arg.html", "structCatch_1_1Clara_1_1Detail_1_1fake__arg" ],
          [ "HelpColumns", "structCatch_1_1Clara_1_1Detail_1_1HelpColumns.html", "structCatch_1_1Clara_1_1Detail_1_1HelpColumns" ],
          [ "LambdaInvoker", "structCatch_1_1Clara_1_1Detail_1_1LambdaInvoker.html", null ],
          [ "LambdaInvoker< void >", "structCatch_1_1Clara_1_1Detail_1_1LambdaInvoker_3_01void_01_4.html", null ],
          [ "ParserBase", "classCatch_1_1Clara_1_1Detail_1_1ParserBase.html", "classCatch_1_1Clara_1_1Detail_1_1ParserBase" ],
          [ "ParserRefImpl", "classCatch_1_1Clara_1_1Detail_1_1ParserRefImpl.html", "classCatch_1_1Clara_1_1Detail_1_1ParserRefImpl" ],
          [ "ParseState", "classCatch_1_1Clara_1_1Detail_1_1ParseState.html", "classCatch_1_1Clara_1_1Detail_1_1ParseState" ],
          [ "ResultBase", "classCatch_1_1Clara_1_1Detail_1_1ResultBase.html", "classCatch_1_1Clara_1_1Detail_1_1ResultBase" ],
          [ "ResultValueBase", "classCatch_1_1Clara_1_1Detail_1_1ResultValueBase.html", "classCatch_1_1Clara_1_1Detail_1_1ResultValueBase" ],
          [ "ResultValueBase< void >", "classCatch_1_1Clara_1_1Detail_1_1ResultValueBase_3_01void_01_4.html", "classCatch_1_1Clara_1_1Detail_1_1ResultValueBase_3_01void_01_4" ],
          [ "Token", "structCatch_1_1Clara_1_1Detail_1_1Token.html", "structCatch_1_1Clara_1_1Detail_1_1Token" ],
          [ "TokenStream", "classCatch_1_1Clara_1_1Detail_1_1TokenStream.html", "classCatch_1_1Clara_1_1Detail_1_1TokenStream" ],
          [ "UnaryLambdaTraits", "structCatch_1_1Clara_1_1Detail_1_1UnaryLambdaTraits.html", null ],
          [ "UnaryLambdaTraits< ReturnT(ClassT::*)(Args...) const >", "structCatch_1_1Clara_1_1Detail_1_1UnaryLambdaTraits_3_01ReturnT_07ClassT_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
          [ "UnaryLambdaTraits< ReturnT(ClassT::*)(ArgT) const >", "structCatch_1_1Clara_1_1Detail_1_1UnaryLambdaTraits_3_01ReturnT_07ClassT_1_1_5_08_07ArgT_08_01const_01_4.html", "structCatch_1_1Clara_1_1Detail_1_1UnaryLambdaTraits_3_01ReturnT_07ClassT_1_1_5_08_07ArgT_08_01const_01_4" ]
        ] ],
        [ "accept_many_t", "structCatch_1_1Clara_1_1accept__many__t.html", null ],
        [ "Arg", "classCatch_1_1Clara_1_1Arg.html", "classCatch_1_1Clara_1_1Arg" ],
        [ "Args", "classCatch_1_1Clara_1_1Args.html", "classCatch_1_1Clara_1_1Args" ],
        [ "ExeName", "classCatch_1_1Clara_1_1ExeName.html", "classCatch_1_1Clara_1_1ExeName" ],
        [ "Help", "structCatch_1_1Clara_1_1Help.html", "structCatch_1_1Clara_1_1Help" ],
        [ "Opt", "classCatch_1_1Clara_1_1Opt.html", "classCatch_1_1Clara_1_1Opt" ],
        [ "Parser", "classCatch_1_1Clara_1_1Parser.html", "classCatch_1_1Clara_1_1Parser" ]
      ] ],
      [ "Detail", "namespaceCatch_1_1Detail.html", [
        [ "conjunction", "structCatch_1_1Detail_1_1conjunction.html", null ],
        [ "conjunction< B1 >", "structCatch_1_1Detail_1_1conjunction_3_01B1_01_4.html", null ],
        [ "conjunction< B1, Bn... >", "structCatch_1_1Detail_1_1conjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
        [ "disjunction", "structCatch_1_1Detail_1_1disjunction.html", null ],
        [ "disjunction< B1 >", "structCatch_1_1Detail_1_1disjunction_3_01B1_01_4.html", null ],
        [ "disjunction< B1, Bn... >", "structCatch_1_1Detail_1_1disjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
        [ "EnumInfo", "structCatch_1_1Detail_1_1EnumInfo.html", "structCatch_1_1Detail_1_1EnumInfo" ],
        [ "is_range_impl", "structCatch_1_1Detail_1_1is__range__impl.html", null ],
        [ "is_range_impl< T, void_t< decltype(begin(std::declval< T >()))> >", "structCatch_1_1Detail_1_1is__range__impl_3_01T_00_01void__t_3_01decltype_07begin_07std_1_1declval_3_01T_01_4_07_08_08_08_4_01_4.html", null ],
        [ "make_void", "structCatch_1_1Detail_1_1make__void.html", "structCatch_1_1Detail_1_1make__void" ],
        [ "negation", "structCatch_1_1Detail_1_1negation.html", null ],
        [ "NonCopyable", "classCatch_1_1Detail_1_1NonCopyable.html", "classCatch_1_1Detail_1_1NonCopyable" ],
        [ "priority_tag", "structCatch_1_1Detail_1_1priority__tag.html", null ],
        [ "priority_tag< 0 >", "structCatch_1_1Detail_1_1priority__tag_3_010_01_4.html", null ],
        [ "unique_ptr", "classCatch_1_1Detail_1_1unique__ptr.html", "classCatch_1_1Detail_1_1unique__ptr" ]
      ] ],
      [ "Generators", "namespaceCatch_1_1Generators.html", [
        [ "as", "structCatch_1_1Generators_1_1as.html", null ],
        [ "ChunkGenerator", "classCatch_1_1Generators_1_1ChunkGenerator.html", "classCatch_1_1Generators_1_1ChunkGenerator" ],
        [ "FilterGenerator", "classCatch_1_1Generators_1_1FilterGenerator.html", "classCatch_1_1Generators_1_1FilterGenerator" ],
        [ "FixedValuesGenerator", "classCatch_1_1Generators_1_1FixedValuesGenerator.html", "classCatch_1_1Generators_1_1FixedValuesGenerator" ],
        [ "Generators", "classCatch_1_1Generators_1_1Generators.html", "classCatch_1_1Generators_1_1Generators" ],
        [ "GeneratorUntypedBase", "classCatch_1_1Generators_1_1GeneratorUntypedBase.html", "classCatch_1_1Generators_1_1GeneratorUntypedBase" ],
        [ "GeneratorWrapper", "classCatch_1_1Generators_1_1GeneratorWrapper.html", "classCatch_1_1Generators_1_1GeneratorWrapper" ],
        [ "IGenerator", "classCatch_1_1Generators_1_1IGenerator.html", "classCatch_1_1Generators_1_1IGenerator" ],
        [ "MapGenerator", "classCatch_1_1Generators_1_1MapGenerator.html", "classCatch_1_1Generators_1_1MapGenerator" ],
        [ "RepeatGenerator", "classCatch_1_1Generators_1_1RepeatGenerator.html", "classCatch_1_1Generators_1_1RepeatGenerator" ],
        [ "SingleValueGenerator", "classCatch_1_1Generators_1_1SingleValueGenerator.html", "classCatch_1_1Generators_1_1SingleValueGenerator" ],
        [ "TakeGenerator", "classCatch_1_1Generators_1_1TakeGenerator.html", "classCatch_1_1Generators_1_1TakeGenerator" ]
      ] ],
      [ "always_false", "structCatch_1_1always__false.html", null ],
      [ "Approx", "classCatch_1_1Approx.html", "classCatch_1_1Approx" ],
      [ "AssertionHandler", "classCatch_1_1AssertionHandler.html", "classCatch_1_1AssertionHandler" ],
      [ "AssertionInfo", "structCatch_1_1AssertionInfo.html", "structCatch_1_1AssertionInfo" ],
      [ "AssertionReaction", "structCatch_1_1AssertionReaction.html", "structCatch_1_1AssertionReaction" ],
      [ "AssertionResult", "classCatch_1_1AssertionResult.html", "classCatch_1_1AssertionResult" ],
      [ "AssertionResultData", "structCatch_1_1AssertionResultData.html", "structCatch_1_1AssertionResultData" ],
      [ "AutoReg", "structCatch_1_1AutoReg.html", "structCatch_1_1AutoReg" ],
      [ "BenchmarkInfo", "structCatch_1_1BenchmarkInfo.html", "structCatch_1_1BenchmarkInfo" ],
      [ "BenchmarkStats", "structCatch_1_1BenchmarkStats.html", "structCatch_1_1BenchmarkStats" ],
      [ "BinaryExpr", "classCatch_1_1BinaryExpr.html", "classCatch_1_1BinaryExpr" ],
      [ "capture_by_value", "structCatch_1_1capture__by__value.html", null ],
      [ "Config", "classCatch_1_1Config.html", "classCatch_1_1Config" ],
      [ "ConfigData", "structCatch_1_1ConfigData.html", "structCatch_1_1ConfigData" ],
      [ "Context", "classCatch_1_1Context.html", "classCatch_1_1Context" ],
      [ "Counts", "structCatch_1_1Counts.html", "structCatch_1_1Counts" ],
      [ "Decomposer", "structCatch_1_1Decomposer.html", "structCatch_1_1Decomposer" ],
      [ "ExceptionTranslatorRegistrar", "classCatch_1_1ExceptionTranslatorRegistrar.html", "classCatch_1_1ExceptionTranslatorRegistrar" ],
      [ "ExprLhs", "classCatch_1_1ExprLhs.html", "classCatch_1_1ExprLhs" ],
      [ "GeneratorException", "classCatch_1_1GeneratorException.html", "classCatch_1_1GeneratorException" ],
      [ "IConfig", "classCatch_1_1IConfig.html", "classCatch_1_1IConfig" ],
      [ "IExceptionTranslator", "classCatch_1_1IExceptionTranslator.html", "classCatch_1_1IExceptionTranslator" ],
      [ "IExceptionTranslatorRegistry", "classCatch_1_1IExceptionTranslatorRegistry.html", "classCatch_1_1IExceptionTranslatorRegistry" ],
      [ "IGeneratorTracker", "classCatch_1_1IGeneratorTracker.html", "classCatch_1_1IGeneratorTracker" ],
      [ "IMutableEnumValuesRegistry", "classCatch_1_1IMutableEnumValuesRegistry.html", "classCatch_1_1IMutableEnumValuesRegistry" ],
      [ "IMutableRegistryHub", "classCatch_1_1IMutableRegistryHub.html", "classCatch_1_1IMutableRegistryHub" ],
      [ "IRegistryHub", "classCatch_1_1IRegistryHub.html", "classCatch_1_1IRegistryHub" ],
      [ "IResultCapture", "classCatch_1_1IResultCapture.html", "classCatch_1_1IResultCapture" ],
      [ "is_callable", "structCatch_1_1is__callable.html", null ],
      [ "is_callable< Fun(Args...)>", "structCatch_1_1is__callable_3_01Fun_07Args_8_8_8_08_4.html", null ],
      [ "is_callable_tester", "structCatch_1_1is__callable__tester.html", null ],
      [ "is_range", "structCatch_1_1is__range.html", null ],
      [ "ITransientExpression", "classCatch_1_1ITransientExpression.html", "classCatch_1_1ITransientExpression" ],
      [ "LazyExpression", "classCatch_1_1LazyExpression.html", "classCatch_1_1LazyExpression" ],
      [ "MessageInfo", "structCatch_1_1MessageInfo.html", "structCatch_1_1MessageInfo" ],
      [ "NameAndTags", "structCatch_1_1NameAndTags.html", "structCatch_1_1NameAndTags" ],
      [ "Optional", "classCatch_1_1Optional.html", "classCatch_1_1Optional" ],
      [ "ProcessedReporterSpec", "structCatch_1_1ProcessedReporterSpec.html", "structCatch_1_1ProcessedReporterSpec" ],
      [ "ratio_string", "structCatch_1_1ratio__string.html", null ],
      [ "ratio_string< std::atto >", "structCatch_1_1ratio__string_3_01std_1_1atto_01_4.html", null ],
      [ "ratio_string< std::femto >", "structCatch_1_1ratio__string_3_01std_1_1femto_01_4.html", null ],
      [ "ratio_string< std::micro >", "structCatch_1_1ratio__string_3_01std_1_1micro_01_4.html", null ],
      [ "ratio_string< std::milli >", "structCatch_1_1ratio__string_3_01std_1_1milli_01_4.html", null ],
      [ "ratio_string< std::nano >", "structCatch_1_1ratio__string_3_01std_1_1nano_01_4.html", null ],
      [ "ratio_string< std::pico >", "structCatch_1_1ratio__string_3_01std_1_1pico_01_4.html", null ],
      [ "RegistrarForTagAliases", "structCatch_1_1RegistrarForTagAliases.html", "structCatch_1_1RegistrarForTagAliases" ],
      [ "ResultDisposition", "structCatch_1_1ResultDisposition.html", "structCatch_1_1ResultDisposition" ],
      [ "ResultWas", "structCatch_1_1ResultWas.html", "structCatch_1_1ResultWas" ],
      [ "Section", "classCatch_1_1Section.html", "classCatch_1_1Section" ],
      [ "SectionEndInfo", "structCatch_1_1SectionEndInfo.html", "structCatch_1_1SectionEndInfo" ],
      [ "SectionInfo", "structCatch_1_1SectionInfo.html", "structCatch_1_1SectionInfo" ],
      [ "Session", "classCatch_1_1Session.html", "classCatch_1_1Session" ],
      [ "SimplePcg32", "classCatch_1_1SimplePcg32.html", "classCatch_1_1SimplePcg32" ],
      [ "SourceLineInfo", "structCatch_1_1SourceLineInfo.html", "structCatch_1_1SourceLineInfo" ],
      [ "StringMaker", "structCatch_1_1StringMaker.html", null ],
      [ "StringMaker< bool >", "structCatch_1_1StringMaker_3_01bool_01_4.html", null ],
      [ "StringMaker< Catch::Approx >", "structCatch_1_1StringMaker_3_01Catch_1_1Approx_01_4.html", null ],
      [ "StringMaker< char * >", "structCatch_1_1StringMaker_3_01char_01_5_01_4.html", null ],
      [ "StringMaker< char >", "structCatch_1_1StringMaker_3_01char_01_4.html", null ],
      [ "StringMaker< char const * >", "structCatch_1_1StringMaker_3_01char_01const_01_5_01_4.html", null ],
      [ "StringMaker< char[SZ]>", "structCatch_1_1StringMaker_3_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< double >", "structCatch_1_1StringMaker_3_01double_01_4.html", null ],
      [ "StringMaker< float >", "structCatch_1_1StringMaker_3_01float_01_4.html", null ],
      [ "StringMaker< int >", "structCatch_1_1StringMaker_3_01int_01_4.html", null ],
      [ "StringMaker< long >", "structCatch_1_1StringMaker_3_01long_01_4.html", null ],
      [ "StringMaker< long long >", "structCatch_1_1StringMaker_3_01long_01long_01_4.html", null ],
      [ "StringMaker< R C::* >", "structCatch_1_1StringMaker_3_01R_01C_1_1_5_01_4.html", null ],
      [ "StringMaker< R, std::enable_if_t< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable_v< R > > >", "structCatch_1_1StringMaker_3_01R_00_01std_1_1enable__if__t_3_01is__range_3_01R_01_4_1_1value_01_32c3977071ebf35680b5962ea44d3bb7.html", null ],
      [ "StringMaker< signed char >", "structCatch_1_1StringMaker_3_01signed_01char_01_4.html", null ],
      [ "StringMaker< signed char[SZ]>", "structCatch_1_1StringMaker_3_01signed_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< std::chrono::duration< Value, Ratio > >", "structCatch_1_1StringMaker_3_01std_1_1chrono_1_1duration_3_01Value_00_01Ratio_01_4_01_4.html", null ],
      [ "StringMaker< std::chrono::duration< Value, std::ratio< 1 > > >", "structCatch_1_1StringMaker_3_01std_1_1chrono_1_1duration_3_01Value_00_01std_1_1ratio_3_011_01_4_01_4_01_4.html", null ],
      [ "StringMaker< std::chrono::duration< Value, std::ratio< 3600 > > >", "structCatch_1_1StringMaker_3_01std_1_1chrono_1_1duration_3_01Value_00_01std_1_1ratio_3_013600_01_4_01_4_01_4.html", null ],
      [ "StringMaker< std::chrono::duration< Value, std::ratio< 60 > > >", "structCatch_1_1StringMaker_3_01std_1_1chrono_1_1duration_3_01Value_00_01std_1_1ratio_3_0160_01_4_01_4_01_4.html", null ],
      [ "StringMaker< std::chrono::time_point< Clock, Duration > >", "structCatch_1_1StringMaker_3_01std_1_1chrono_1_1time__point_3_01Clock_00_01Duration_01_4_01_4.html", null ],
      [ "StringMaker< std::chrono::time_point< std::chrono::system_clock, Duration > >", "structCatch_1_1StringMaker_3_01std_1_1chrono_1_1time__point_3_01std_1_1chrono_1_1system__clock_00_01Duration_01_4_01_4.html", null ],
      [ "StringMaker< std::nullptr_t >", "structCatch_1_1StringMaker_3_01std_1_1nullptr__t_01_4.html", null ],
      [ "StringMaker< std::string >", "structCatch_1_1StringMaker_3_01std_1_1string_01_4.html", null ],
      [ "StringMaker< std::wstring >", "structCatch_1_1StringMaker_3_01std_1_1wstring_01_4.html", null ],
      [ "StringMaker< T * >", "structCatch_1_1StringMaker_3_01T_01_5_01_4.html", null ],
      [ "StringMaker< T[SZ]>", "structCatch_1_1StringMaker_3_01T_0fSZ_0e_4.html", null ],
      [ "StringMaker< unsigned char >", "structCatch_1_1StringMaker_3_01unsigned_01char_01_4.html", null ],
      [ "StringMaker< unsigned char[SZ]>", "structCatch_1_1StringMaker_3_01unsigned_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< unsigned int >", "structCatch_1_1StringMaker_3_01unsigned_01int_01_4.html", null ],
      [ "StringMaker< unsigned long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01_4.html", null ],
      [ "StringMaker< unsigned long long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01long_01_4.html", null ],
      [ "StringMaker< wchar_t * >", "structCatch_1_1StringMaker_3_01wchar__t_01_5_01_4.html", null ],
      [ "StringMaker< wchar_t const * >", "structCatch_1_1StringMaker_3_01wchar__t_01const_01_5_01_4.html", null ],
      [ "StringRef", "classCatch_1_1StringRef.html", "classCatch_1_1StringRef" ],
      [ "Tag", "structCatch_1_1Tag.html", "structCatch_1_1Tag" ],
      [ "TestCaseHandle", "classCatch_1_1TestCaseHandle.html", "classCatch_1_1TestCaseHandle" ],
      [ "TestCaseInfo", "structCatch_1_1TestCaseInfo.html", "structCatch_1_1TestCaseInfo" ],
      [ "TestFailureException", "structCatch_1_1TestFailureException.html", null ],
      [ "TestInvokerAsMethod", "classCatch_1_1TestInvokerAsMethod.html", "classCatch_1_1TestInvokerAsMethod" ],
      [ "TestInvokerFixture", "classCatch_1_1TestInvokerFixture.html", "classCatch_1_1TestInvokerFixture" ],
      [ "TestRunInfo", "structCatch_1_1TestRunInfo.html", "structCatch_1_1TestRunInfo" ],
      [ "TestSkipException", "structCatch_1_1TestSkipException.html", null ],
      [ "Timer", "classCatch_1_1Timer.html", "classCatch_1_1Timer" ],
      [ "Totals", "structCatch_1_1Totals.html", "structCatch_1_1Totals" ],
      [ "true_given", "structCatch_1_1true__given.html", null ],
      [ "UnaryExpr", "classCatch_1_1UnaryExpr.html", "classCatch_1_1UnaryExpr" ],
      [ "Version", "structCatch_1_1Version.html", "structCatch_1_1Version" ],
      [ "WaitForKeypress", "structCatch_1_1WaitForKeypress.html", "structCatch_1_1WaitForKeypress" ],
      [ "WarnAbout", "structCatch_1_1WarnAbout.html", "structCatch_1_1WarnAbout" ],
      [ "WildcardPattern", "classCatch_1_1WildcardPattern.html", "classCatch_1_1WildcardPattern" ]
    ] ],
    [ "BalancedBST", "classBalancedBST.html", "classBalancedBST" ],
    [ "BinarySearchTree", "classBinarySearchTree.html", "classBinarySearchTree" ],
    [ "Catch_global_namespace_dummy", "structCatch__global__namespace__dummy.html", null ],
    [ "Graph", "classGraph.html", "classGraph" ],
    [ "TestBalancedBST", "classTestBalancedBST.html", "classTestBalancedBST" ]
];